In [1]:
import numpy as np

In [4]:
inputs = [[1, 2, 3, 4],
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -0.8]]

# layer 1 " single neuron"
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
"layer 1 output dim 3x3"

# layer 2
weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]
"layer 2 o/p dim 3x3"


layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
# input shape is broadcasted by duplicated the row 
print("Output:\n",layer2_outputs,"\n", "Output layer dim:", layer2_outputs.shape)


Output:
 [[ 1.6706  -2.4841  -3.4835 ]
 [ 0.7634  -3.0764  -5.8985 ]
 [-1.38314  1.66994 -0.25515]] 
 Output layer dim: (3, 3)


In [10]:
np.random.seed(42)

X = [[1, 2, 3, 4],
    [2, 5, -1, 2],
    [-1.5, 2.7, 3.3, -0.8]]

class layer_Dense:
    def __init__(self, n_inputs = None, n_neuron = None):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neuron) # gaussian distro
        # by initializing weights as i/p, n_neuron avoids the transpose in the forward pass

        self.biases = np.zeros((1, n_neuron))
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = layer_Dense(n_inputs= 4, n_neuron = 5)
layer2 = layer_Dense(n_inputs= 5, n_neuron= 2)

layer1.forward(X)
print("output of layer1:\n",layer1.output)

layer2.forward(layer1.output)
print("output of layer 2: \n", layer2.output)

output of layer1:
 [[-0.3610963  -0.24283524  0.41654341 -0.8787856  -0.99730016]
 [-0.08384138  0.6059603   0.55190831  0.07959199  0.11448039]
 [-0.24566894  0.37446278  0.16476186 -0.91395312 -0.27462437]]
output of layer 2: 
 [[ 0.0838096   0.04344583]
 [-0.05427832 -0.0786683 ]
 [ 0.07924331 -0.07230373]]


## 5. Hidden Layer Activation Functions